"""Markdown and JSON report generator for redactron runs.

Writes <output>.report.md and <output>.report.json alongside the redacted PDF.
Can also re-render from an audit DB row via render_from_db().

BLD-16 (M3.4)
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from redactron.audit.log import DocumentRecord


def render_markdown(record: DocumentRecord) -> str:
    """Render a DocumentRecord as a Markdown report string.

    Args:
        record: The run record to render.

    Returns:
        Markdown string.
    """
    verification_line = "N/A (skipped)"
    if record.verification_passed is True:
        verification_line = "✅ Passed — no PII survivors detected"
    elif record.verification_passed is False:
        n = len(record.verification_survivors)
        verification_line = f"❌ Failed — {n} PII item(s) survived redaction"

    survivors_section = ""
    if record.verification_survivors:
        items = "\n".join(f"- `{s}`" for s in record.verification_survivors)
        survivors_section = f"\n## Survivors\n\n{items}\n"

    subject_line = f"**Subject:** {record.subject_id}" if record.subject_id else ""
    processed = (
        record.processed_at.isoformat()
        if isinstance(record.processed_at, datetime)
        else str(record.processed_at)
    )

    return f"""\
# Redactron Report

**File:** {record.original_filename}
**Output:** {record.output_filename}
**Profile:** {record.profile_name}
{subject_line}
**Processed:** {processed}
**Duration:** {record.duration_ms} ms

## Summary

| Metric | Value |
|--------|-------|
| Pages processed | {record.pages_processed} |
| Items detected | {record.items_detected} |
| Items redacted | {record.items_redacted} |
| Verification | {verification_line} |
{survivors_section}
---
*Generated by redactron*
""".strip()


def render_json(record: DocumentRecord) -> str:
    """Render a DocumentRecord as a JSON string.

    Args:
        record: The run record to render.

    Returns:
        JSON string.
    """
    processed_at = (
        record.processed_at.isoformat()
        if isinstance(record.processed_at, datetime)
        else str(record.processed_at)
    )
    data = {
        "original_filename": record.original_filename,
        "output_filename": record.output_filename,
        "profile_name": record.profile_name,
        "subject_id": record.subject_id,
        "processed_at": processed_at,
        "duration_ms": record.duration_ms,
        "pages_processed": record.pages_processed,
        "items_detected": record.items_detected,
        "items_redacted": record.items_redacted,
        "verification_passed": record.verification_passed,
        "verification_survivors": record.verification_survivors,
        "notes": record.notes,
    }
    return json.dumps(data, indent=2)


def write_reports(record: DocumentRecord, output_pdf: Path) -> tuple[Path, Path]:
    """Write .report.md and .report.json alongside the redacted PDF.

    Args:
        record: The run record.
        output_pdf: Path to the redacted PDF.

    Returns:
        Tuple of (md_path, json_path).
    """
    stem = output_pdf.with_suffix("")
    md_path = stem.with_suffix(".report.md")
    json_path = stem.with_suffix(".report.json")
    md_path.write_text(render_markdown(record), encoding="utf-8")
    json_path.write_text(render_json(record), encoding="utf-8")
    return md_path, json_path


def write_batch_summary(
    results: list[dict],  # type: ignore[type-arg]
    errors: list,  # type: ignore[type-arg]  # list[BatchFileError]
    reports_dir: Path,
    run_ts: str,
) -> tuple[Path, Path]:
    """Write a consolidated batch summary report.

    Args:
        results: List of per-file result dicts from _run_pipeline.
        errors: List of BatchFileError objects.
        reports_dir: Directory to write reports into.
        run_ts: Timestamp string YYYY-MM-DD-HHMM for the filename.

    Returns:
        Tuple of (md_path, json_path).
    """
    reports_dir.mkdir(parents=True, exist_ok=True)
    md_path = reports_dir / f"{run_ts}_batch-summary.md"
    json_path = reports_dir / f"{run_ts}_batch-summary.json"

    n_ok = len(results)
    n_err = len(errors)
    total = n_ok + n_err

    # Markdown
    rows_md = []
    for r in results:
        inp = Path(str(r["input"])).name
        out = Path(str(r["output"])).name
        det = r["detections"]
        vf = r.get("verification")
        if vf is None:
            vstatus = "—"
        elif isinstance(vf, dict) and vf.get("passed"):
            vstatus = "✅"
        else:
            vstatus = "❌"
        rows_md.append(f"| ✓ | {inp} | {out} | {det} | {vstatus} |")
    for e in errors:
        rows_md.append(f"| ✗ | {e.path.name} | — | — | [{e.category}] {e.mitigation} |")

    table = "\n".join(rows_md)
    md = f"""\
# Redactron Batch Summary

**Run:** {run_ts}  **Total:** {total}  **OK:** {n_ok}  **Errors:** {n_err}

| Status | File | Output | Detections | Verification |
|--------|------|--------|------------|--------------|
{table}

---
*Generated by redactron*
"""
    md_path.write_text(md, encoding="utf-8")

    # JSON
    data = {
        "run_ts": run_ts,
        "total": total,
        "ok": n_ok,
        "errors": n_err,
        "results": [
            {
                "input": str(r["input"]),
                "output": str(r["output"]),
                "detections": r["detections"],
                "verification": r.get("verification"),
            }
            for r in results
        ],
        "failures": [
            {
                "path": str(e.path),
                "category": e.category,
                "message": e.message,
                "mitigation": e.mitigation,
            }
            for e in errors
        ],
    }
    json_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return md_path, json_path


def render_from_db(row: dict) -> str:  # type: ignore[type-arg]
    """Re-render a Markdown report from an audit DB row dict.

    Args:
        row: A dict as returned by audit.log.get_runs().

    Returns:
        Markdown string.
    """
    import json as _json

    survivors = _json.loads(row.get("verification_survivors_json") or "[]")
    vp = row.get("verification_passed")
    record = DocumentRecord(
        file_hash=row.get("file_hash", ""),
        original_filename=row.get("original_filename", ""),
        output_filename=row.get("output_filename", ""),
        profile_name=row.get("profile_name", ""),
        subject_id=row.get("subject_id", ""),
        pages_processed=row.get("pages_processed", 0),
        items_detected=row.get("items_detected", 0),
        items_redacted=row.get("items_redacted", 0),
        verification_passed=bool(vp) if vp is not None else None,
        verification_survivors=survivors,
        duration_ms=row.get("duration_ms", 0),
        notes=row.get("notes", ""),
        processed_at=datetime.fromisoformat(row["processed_at"])
        if row.get("processed_at")
        else datetime.now(UTC),
    )
    return render_markdown(record)
